name: Ad Hoc Reporting Automation

# Trigger the workflow on a schedule (every Monday at 9 AM) or manually
on:
  schedule:
    - cron: '0 9 * * 1'  # Every Monday at 9 AM
  workflow_dispatch:  # Allows you to trigger it manually from GitHub

jobs:
  run-reporting-script:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Pulls your repository code

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Ad Hoc Reporting Script
        run: |
          python3 ad_hoc_reporting.py
